### ISSUE TITLE
Possessive to indicate owner, part

### ISSUE THREAD

**Issue by arthalun** [nickmontfort/curveship-js#33]
As I understand, the current system does not specify the ownership of the things in the process of realizing the sentences. For instance, in the Story of an Hour, "She immediately weeps," if we are to indicate whose arms (as the original story does) the current system wouldn't realize it as "She immediately weeps in her arms" even if set the ownership of arms (thing) to Josephine (actor)

**Comment by nickmontfort** [comment]
I will add that by default (and for now, in the only style of narration), the *parts* of an Existent are to be represented using the parent Existent's possessive. That is, if we have a seat that is part of a bike, when it is realized in a sentence it should be realized as "the bike’s seat."

Be default we will add ’s to make something possessive (unless pronominalizing), but there are special cases such as Moses’ tablets, Jesus’ son, etc. These cannot all be detected by looking at the last letter, because this rule is only used for religious names, so it's Borges’s library.

**Comment by nickmontfort** [comment]
test case added at test/possessives

**Comment by nickmontfort** [comment]
"A woman sighs." in the test case needs to be "The woman sighs." actor.mary has to be added to givens.
