### ISSUE TITLE
Use of realized pronouns differ despite being declared the same way

### ISSUE THREAD

**Issue by anjchang** [nickmontfort/curveship-js#35]
I expect that specifying a gender pronoun in `Names` would result in gender specific output.
In tmp/henny/story.js, I have the following actor:
<pre>actor.henny = new Actor(place.farmyard, "female");
ev.decides = new Event(actor.henny);</pre>
In two narrator files, I have the verb phrase:
<pre>
vp.decides = new VerbPh("decide to tell the king");</pre>
In the first narration  tmp/henny/casual.html, I declare the names
<pre>
names.henny = new ProperNames("Henny","Penny", pronoun.feminine, "a chicken");
</pre>
In the second narration tmp/henny/henny_vfws.html, I declare the name very similarly
<pre>
names.henny = new Names("Hen","Pen", pronoun.feminine, "a chicken");
</pre>
But when I run the curveship, I get the gender specific pronoun 'she', and in the other case, I get a generic pronoun 'it.'
In tmp/henny/henny_vfws.html<pre>
It decides to tell the king.</pre>
In tmp/henny/casual.html,
<pre>She decides to tell the king.</pre>
Shouldn't they both use the gender specific pronoun 'She"?

**Comment by nickmontfort** [comment]
You haven't declared the names in the same way. Please correct a few things and see if the issue persists.

1. `vp.decides = new VerbPh("decide to tell the king");` This is not the correct way to specify a VerbPh. While it's true that in linguistics a verb phrase includes its object ("the king") a VerbPh in Curveship does not. You should have two arguments to ev.decides, and the second one should be actor.king. The VerbPh should be "decides to tell"
2. `names.henny = new ProperNames("Henny","Penny", pronoun.feminine, "a chicken");` You need to have `pronoun.female` instead of `pronoun.feminine` although an enhancement could be to allow masculine and feminine to mean the same thing as male as female.
3. `names.henny = new Names("Hen","Pen", pronoun.feminine, "a chicken");` Names has a different interface than ProperNames and takes at most three arguments: initial, subsequent, and pronouns. You probably don't want to call this character "Hen" the first time and "Pen" thereafter as this would be very confusing. Again, you need to use `pronoun.female` right now.

I'm assigning this issue to you so that you can fix the problems in your tmp/henny and then clarify what the issue is, if there is one. For instance if we need to change the interfaces of Names and ProperNames to avoid confusion, we can. If we want to have pronouns.feminine be the same thing as pronouns.female, we can.

**Comment by anjchang** [comment]
Okay, I changed it and everything is fine now.
