### ISSUE TITLE
Title of the narrator html file seems to be ignored 

### ISSUE THREAD

**Issue by anjchang** [nickmontfort/curveship-js#37]
The "title" of the narrator files seem to be using the title from the story.js files. It seems more useful for the narrator files to use the `title` set in each narrator.js file.

**Comment by nickmontfort** [comment]
It's correct as is. The "title" as set with `let title =` in the story.js file is the title of the underlying story or content, as in "Little Red Riding Hood" or to use one of our example story files,

`let told_by = "a casual, very oblique narrator";`

Each narrator file has a `told_by` variable (which I will change to toldBy soon), e.g.,

`let told_by = "a casual, very oblique narrator";`

This lets us see that the same story (the one with a title) can be told different ways by different narrators. To give each *telling* a different title would make it harder to understand narrative theory.

The html file also has a title element, by the way, and it's the author's responsibility to make sure this title aligns appropriately because it's what shows up in tabs/bookmarks.
