### ISSUE TITLE
Subsequent references are not working in Whale

### ISSUE THREAD

**Issue by arthalun** [nickmontfort/curveship-js#42]
@nickmontfort I tried a few things to figure out why the subsequent references are not called anymore in the Whale story but couldn't find out. Would you take a look at it and see what's up? I gave it a try and used the duplicate files on a previous version of Curveship that we had a couple of days ago, and it worked perfectly fine, not sure what new changes in the system are causing this.

**Comment by nickmontfort** [comment]
There is no case where subsequent names should appear in the whale story. The system has been upgraded so that pronominalization is now done.

_He stabs the whale.
He enters it._

That's correct.

_He has a laminated card in hand.
He and John stare at it._

That's also correct.

If you want the narrator to say “the beast” and “the card” you need to have the whale and the card mentioned at some point when they weren't just mentioned in the previous sentence.

**Comment by arthalun** [comment]
Oh, I see! But wouldn't it look odd and confusing in cases when we have two existent of the same type (and gender if applicable) in action back to back?

For instance, in the _Image_ story, there's a place where this happens:

_A dragon lives in an image.
It burns.
It births the dragon.
**It melts it._**

The last event becomes confusing and misleading about which one melts the other one. (_It melts it_)
Although, it might actually creating an interesting effect when someone gets to interact with the rest of the system to figure out the answer to that uncertainty by changing i and you or other intervention.

**Comment by nickmontfort** [comment]
As an enhancement, we can add a global spin parameter that causes the system to pronominalize more or less. That would allow an adjustment that avoids the ambiguity there.
There are plenty of real-life cases of felicitous English where people pronominalize both subject and object, and sometimes you have to understand context/semantics to figure out what is being said. For instance:
"John called Bill a Republican.
"Then he hit him."
Perfectly good exchange, but we have to know some about John and Bill, their politics, their proclivities for violence, etc., in order to figure out what the second sentence means.
