### ISSUE TITLE
Complete start.html, Getting Started

### ISSUE THREAD

**Issue by nickmontfort** [nickmontfort/curveship-js#48]
The larger section explaining casual.js needs to be written, followed by a brief explanation of casual.html and how it connects the story and narrator files.

**Comment by anjchang** [comment]
Added the start.html.

**Comment by nickmontfort** [comment]
Thanks for this initial work. This will be a back-and-forth process because I'll need to revise `robbery` to make it a good example.

Please read through the beginning of `start.html` and take a look at how I have put every line from `robbery/story.js` in the `start.html` file, explaining particular lines and providing the other ones to complete the context.

When you continue work on this, check out my inline comments (marked FIXME) and include every line of `robbery/casual.js` in the second section of `start.html.`

Right now there is no other narrator file for The Simulated Bank Robbery, but that will have to change. I’ll add one, and we can then refer to it (not including every line, but just making mention of parts of the file) in `start.html.`

**Comment by anjchang** [comment]
Understood, thank you!

**Comment by anjchang** [comment]
Okay, I've edited start.html to follow the robbery example more closely. I suggest adding a technical reference for ProperNames, rather than diving into that in the Start.html because the current example (robbery) does not have that example. If we moved talking in detail about ProperNames to the technical reference, we could devote the discussion to the hour example. Will start an "issue" for that.
