### ISSUE TITLE
Adding ProperNames to the technical reference

### ISSUE THREAD

**Issue by anjchang** [nickmontfort/curveship-js#58]
Suggest adding a technical reference for ProperNames in reference.html, rather than diving into that in the Start.html because the current start example (robbery) does not use ProperNames. If we moved talking in detail about ProperNames to the technical reference, we could devote the discussion to the hour example in the technical reference.  Then start.html can be devoted to the robbery example.

**Comment by nickmontfort** [comment]
Getting Started needs to go through a single example that covers all the basics. Otherwise it won't help people get started. The right way to deal with this is to just add ProperNames for one Actor (e.g., the robbery) in The Simulated Bank Robbery.

We also need to include a few examples of spin, used in robbery, in Getting Started, although we won't be able to be exhaustive in any one narrator file.
